dist: xenial

language: php

php:
  - 7.4

git:
  depth: 5

cache:
  npm: true
  yarn: true

services:
  - mysql

before_install:
  - nvm install 14

install:
  - yarn install

script:
  - yarn run wp19-test
