definitions:
  script: &ssh_prepare mkdir -p ~/.ssh && echo $KNOWNHOSTS > ~/.ssh/known_hosts && (umask  077 ; echo $LAB19_STAGE_KEY_B64 | base64 --decode > ~/.ssh/id_rsa)
  steps: &steps
    - step:
        name: Set environment variables
        image: node:10.15.0
        script:
          - THEME=$(node -e "process.stdout.write(JSON.parse(fs.readFileSync('theme.json', 'utf8')).theme)")
          - SITE_DIR="/var/www/$BITBUCKET_BRANCH-$BITBUCKET_REPO_SLUG"
          - COMMIT_MESSAGE=`git log --format=%B -n 1 $BITBUCKET_COMMIT`
          - echo "export THEME=\"$THEME\" ; " >> set_env.sh
          - echo "export SITE_DIR=\"$SITE_DIR\" ; " >> set_env.sh
          - echo "export COMMIT_MESSAGE=\"$COMMIT_MESSAGE\" ; " >> set_env.sh
        artifacts:
          - set_env.sh
    - parallel:
      - step:
          name: Yarn install
          image: node:10.15.0
          script:
            - source set_env.sh
            - yarn install
            - yarn run build
          caches:
            - node
          artifacts:
            - wp-content/themes/**/dist/**
      - step:
          name: Deploy using git
          script:
            - source set_env.sh
            - *ssh_prepare
            - >
              ssh lab19@$LAB19_STAGE_IP "echo \"Create site directory at $SITE_DIR \" ;
              mkdir -p $SITE_DIR ;

              echo \"Git pull from origin\" ;
              cd $SITE_DIR/ ;
              git init . &&
              git pull $BITBUCKET_GIT_SSH_ORIGIN $BITBUCKET_BRANCH ;

              echo \"Copy latest WordPress files to project \" ;
              cd /var/opt/wordpress && git pull origin master &&
              git archive master | tar -x -C $SITE_DIR/ &&
              cp $SITE_DIR/wp-config-staging.php $SITE_DIR/wp-config.php ;

              echo \"Create database\" ;
              bash /var/opt/scripts/create-db.sh $BITBUCKET_REPO_SLUG ;

              echo \"Set directory group permissions\" ;
              sudo chgrp -R www $SITE_DIR ;
              sudo chmod g+s . ;

              echo \"Completed deployment!\" ; "

    - step:
        name: Deploy artifacts
        script:
          - source set_env.sh
          - *ssh_prepare
          - scp -r wp-content/themes/$THEME/dist lab19@$LAB19_STAGE_IP:$SITE_DIR/wp-content/themes/$THEME


pipelines:
  branches:
    master: *steps
    develop: *steps
  custom:
    create-ftp:
      - step:
          script:
            - *ssh_prepare
            - ssh lab19@$LAB19_STAGE_IP "bash /var/opt/scripts/create-ftp.sh $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $BB_AUTH_STRING "
            - echo "FTP details should now be available under the repo downloads in xml"
    import-db:
      - variables:
        - name: ZipFilename
      - step:
          script:
            - *ssh_prepare
            - ssh lab19@$LAB19_STAGE_IP "bash /var/opt/scripts/import-db.sh $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $ZipFilename $BB_AUTH_STRING "
    import-plugins:
      - variables:
        - name: ZipFilename
      - step:
          script:
            - *ssh_prepare
            - ssh lab19@$LAB19_STAGE_IP "bash /var/opt/scripts/import-plugins.sh $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $ZipFilename $BB_AUTH_STRING "
    import-uploads:
      - variables:
        - name: ZipFilename
      - step:
          script:
            - *ssh_prepare
            - ssh lab19@$LAB19_STAGE_IP "bash /var/opt/scripts/import-uploads.sh $BITBUCKET_BRANCH $BITBUCKET_REPO_SLUG $ZipFilename $BB_AUTH_STRING "
